### ISSUE TITLE
Add API to read CF_BITMAP

### ISSUE THREAD

**Issue by DoumanAsh** [DoumanAsh/clipboard-win#12]
subj

**Comment by skygate2012** [comment]
Is it possible to write an image file to clipboard currently?

**Comment by DoumanAsh** [comment]
Sadly no, I'm only able to read BMP as `CF_DIB`

I wasn't sure how to write it so I left it for now.
I would welcome help because I'm really not familiar with these aspects on winapi

**Comment by matheuslessarodrigues** [comment]
Is it correct that I saw that the `image` module is not exposed (even included) in the library?
I've recently managed to extract a `CF_BITMAP` from the clipboard. You can check the code here (the `get_clipboard_bitmap` function):
https://github.com/matheuslessarodrigues/copycat/blob/master/src/main.rs

I'm too not familiar with using winapi from rust, but maybe we can work together to implement this feature?
Anyways, thanks for the crate!

**Comment by auyer** [comment]
I've been having such a hard time placing an image in the clipboard, that I decided I'll wait.
At first I was trying to do this with the API directly, but it's really not straight forward.
Since I'm new to both Rust and the `winapi`, I wont be much help implementing it, but I totally support you guys !
I'll be a day one user !

**Comment by DoumanAsh** [comment]
Ok, I'll give it a try on this weekend and will try to implement simple API to serialize BMP into suitable format for clipboard

**Comment by DoumanAsh** [comment]
@matheuslessarodrigues I wasn't able to make `CF_BITMAP` work and only `CF_DIB` works via https://docs.rs/clipboard-win/3.0.2/clipboard_win/struct.Clipboard.html#method.get_dib

**Comment by matheuslessarodrigues** [comment]
I tired using `CF_DIB` however it almost worked: I could not get to generate valid bmp from a print from ShareX.

Also, sorry about this but I just dicovered that the code I posted does NOT work in release mode.
Oh well, I'll try to fix it before you try it.

**Comment by matheuslessarodrigues** [comment]
Just updated the code in https://github.com/matheuslessarodrigues/copycat/blob/master/src/main.rs
After wrapping some unsafe code, I managed to make it work in release mode as well. I think rust was trying to deallocate some
memory twice.

Btw, that code was translated from this: https://docs.microsoft.com/en-us/windows/win32/gdi/storing-an-image

**Comment by DoumanAsh** [comment]
hm you probably could just make PR? :)
I'd just review your code

**Comment by matheuslessarodrigues** [comment]
Just made one! #13

**Comment by DoumanAsh** [comment]
Released as part of `3.1.0`
