### ISSUE TITLE
Make crate no_std

### ISSUE THREAD

**Issue by DuckerMan** [DoumanAsh/clipboard-win#14]

**Comment by DoumanAsh** [comment]
I'm planning to make it `no_std` in 4.0.0
But why would you need it as `no_std`?
It is basically impossible to use outside of windows

**Comment by DuckerMan** [comment]
It's Windows crate, isn't it?

**Comment by DoumanAsh** [comment]
yeah, it is windows only.
there are cross platform crates, but any of these crates require OS so `no_std` is usually not the use case

**Comment by DoumanAsh** [comment]
@DuckerMan I started `4.x` being `no_std`  by default
https://crates.io/crates/clipboard-win/4.0.0-beta.1

**Comment by DuckerMan** [comment]
Hey, thanks!
