### ISSUE TITLE
Expose a way to call raw::set without clearing first

### ISSUE THREAD

**Issue by complexspaces** [DoumanAsh/clipboard-win#18]
Hi there,

I was taking a closer look at the crate and seeing if it'd be possible to replace some internal code with it. We currently use the clipboard exclusion formats (`CanIncludeInClipboardHistory` and  `CanUploadToCloudClipboard`). Just like other formats, you need to call `SetClipboardData` but instead you have to set [a magic value](https://docs.microsoft.com/en-us/windows/win32/dataxchg/clipboard-formats#cloud-clipboard-and-clipboard-history-formats) of `0u32` instead of the actual clipboard data.

This ends up conflicting poorly with `clipboard_win::raw::set` because it clears the clipboard unconditionally before calling `SetClipboardData`, so the clipboard contents that were there get erased.

Would it be possible to expose a function called `set_no_clear` (name nonwithstanding) that does the same thing as `raw::set`, but without the `EmptyClipboard` call?

**Comment by DoumanAsh** [comment]
This is mostly due to small remark in API docs:

> If an application calls OpenClipboard with hwnd set to NULL, EmptyClipboard sets the clipboard owner to NULL; this causes SetClipboardData to fail.

Hence the policy, but as far as I remember it works without clearing clipboard too

> Would it be possible to expose a function called set_no_clear (name nonwithstanding) that does the same thing as raw::set, but without the EmptyClipboard call?

So yes, feel free to create PR for that

**Comment by complexspaces** [comment]
Thanks for the fast reply! I opened https://github.com/DoumanAsh/clipboard-win/pull/19 with the addition.
