### ISSUE TITLE
Why is there an implementation of strlen in this crate?

### ISSUE THREAD

**Issue by aweinstock314** [DoumanAsh/clipboard-win#2]
https://github.com/DoumanAsh/clipboard-win/blob/9abd1c45fe6e881cbdd337fc0f3e15fb503e6816/src/lib.rs#L164-L174

It seems out-of-place for a clipboard library.

**Comment by DoumanAsh** [comment]
Well.. i needed that to calculate size of clipboard text https://github.com/DoumanAsh/clipboard-win/blob/9abd1c45fe6e881cbdd337fc0f3e15fb503e6816/src/wrapper.rs#L155
Though it is obviously should not be exposed to public API but i was lazy to remove it...

**Comment by DoumanAsh** [comment]
Btw, with new version i removed it from public API.
But it is still present for calculating of buffer's lengths...

**Comment by DoumanAsh** [comment]
Do you find my own naive implementation of ```strlen()``` an issue?
