### ISSUE TITLE
Questions on `FileList`

### ISSUE THREAD

**Issue by gyk** [DoumanAsh/clipboard-win#20]
1. Why does `FileList` use `String` to represent paths?  Old versions of clipboard-win use `PathBuf`. When we obtain a list of dropfiles, we would probably like to access them by their path, but `String::from_utf16_lossy` might return an invalid one.
2. Should `FileList` also implement `Setter` trait? There is a use case for copying files from one's own program.

**Comment by DoumanAsh** [comment]
Hmm i dont remember if it was there before, i do not have access to my laptop and will be able look into it only after new years
We definitely should be able to implement setter for it too

**Comment by gyk** [comment]
Thanks for your reply. According to docs.rs at least [v2](https://docs.rs/clipboard-win/2.2.0/clipboard_win/raw/fn.get_file_list.html) and [v3](https://docs.rs/clipboard-win/3.1.1/clipboard_win/raw/fn.get_file_list.html) still uses `PathBuf`.

**Comment by DoumanAsh** [comment]
Ah it is probably i changed my approach to allow user to reuse buffer https://github.com/DoumanAsh/clipboard-win/blob/master/src/raw.rs#L361
I shall make new API for Pathbuf

**Comment by DoumanAsh** [comment]
I've released 4.3.0 featuring missing API
