### ISSUE TITLE
cannot write the empty string to the clipboard

### ISSUE THREAD

**Issue by jabbalaci** [DoumanAsh/clipboard-win#22]
The library works well but I get an error when I try to write the empty string (`""`) to the clipboard. I expected that if I write `""`, I can read back `""`.

Update:

The empty string can be written on the clipboard. The reading back causes the problem. I tried like this:

```rust
let _clip = Clipboard::new_attempts(10).expect("Open clipboard");
let mut output = String::new();
Unicode.read_clipboard(&mut output).expect("Read text");
```
The last line panicks with 'Read text: OS error 127'.

**Comment by DoumanAsh** [comment]
AFAIK it is limitation of winapi
It doesn't allow empty data set, so this library rejects such sets too

**Comment by DoumanAsh** [comment]
@jabbalaci if you can make it work please feel free to create PR

**Comment by jabbalaci** [comment]
Thanks for the answer. I can set the empty string like this:

```rust
fn set_text_windows(text: &str) -> Result<(), &'static str> {
    if text.is_empty() {
        clipboard_win::raw::open().expect("open clipboard");
        clipboard_win::raw::empty().expect("empty clipboard");
        return Ok(());
    }
    // else
    let result = set_clipboard(formats::Unicode, text);
    match result {
        Ok(_) => Ok(()),
        _ => Err("Unicode error"),
    }
}
```

It seems to work. Reading back is the problematic part. A possible solution could be: read back the content of the clipboard in a `Vec<u8>`. If it's an empty vector, then I could return an empty string. If you had a `clipboard_win::raw::is_empty()` function that returns a bool, that would be great.

I have an old C program that I want to rewrite to Rust. With this C program, I can write the empty string and I can read the empty string to/from the clipboard. Here is the relevant part:

```c
#include <windows.h>

typedef char * string;

// copies the given string TO the clipboard
int copyStringToClipboard(string source)
{
    int ok = OpenClipboard(NULL);

    if (!ok)
    {
        return MY_ERROR;
    }
    // else

    HGLOBAL clipbuffer;
    string buffer;
    EmptyClipboard();
    clipbuffer = GlobalAlloc(GMEM_DDESHARE, strlen(source) + 1);
    buffer = (char *)GlobalLock(clipbuffer);
    strcpy(buffer, source);
    GlobalUnlock(clipbuffer);
    SetClipboardData(CF_TEXT, clipbuffer);
    return CloseClipboard();
}

// we suppose there is a string on the clipboard
// this function copies it FROM there
string getStringFromClipboard()
{
    int ok = OpenClipboard(NULL);

    if (!ok)
    {
        return NULL;
    }
    // else

    HANDLE hData = GetClipboardData(CF_TEXT);
    string buffer = (char *)GlobalLock(hData);
    GlobalUnlock(hData);
    CloseClipboard();

    return buffer;
}
```

**Comment by DoumanAsh** [comment]
ah I forgot, we need to include zero at the end of buffer, so even if string is empty you can actually allocate buffer as you need 1 character for zero byte.
So I suppose it should be possible to do

**Comment by DoumanAsh** [comment]
@jabbalaci I also could use just `emty()` when user provides zero input.
But I'm not sure what is more suitable solution

**Comment by DoumanAsh** [comment]
@jabbalaci 

>  If you had a clipboard_win::raw::is_empty() function that returns a bool, that would be great.

Regarding checking if empty you can just use:
https://github.com/DoumanAsh/clipboard-win/blob/master/src/raw.rs#L159=

It allows to check presence of format on clipboard.
It returns None if there is no data or it is 0 sized

**Comment by jabbalaci** [comment]
Thank you! I could solve it:

```rust
fn get_text_windows() -> Result<String, &'static str> {
    let mut output = String::new();
    let _clip = Clipboard::new_attempts(10).expect("Open clipboard");
    let size = clipboard_win::raw::size(formats::CF_TEXT);
    if size.is_none() {
        return Ok(output);
    }
    // else, the clipboard is not empty
    Unicode.read_clipboard(&mut output).expect("Read text");
    Ok(output)
}
```

Maybe an `is_empty()` convenience function could be added in the future.

**Comment by jabbalaci** [comment]
Yes, but I think it's enough if `is_empty()` returns `true` if zero-sized data is set.

I don't really understand what you mean with the second option. If you want to write the empty string to the clipboard if zero-sized data is set, it's not necessary in my opinion.

However, `Unicode.read_clipboard(&mut output).expect("Read text");` could return the empty string if zero-sized data is set. It seems intuitive to me.

**Comment by DoumanAsh** [comment]
in C language, even zero sized string has 1 character which is null character.
It is not visible, but it is used as sort of EOF detection in string.
Hence if you pass Rust's empty string, it will be `"\0"` in C which is zero sized, but buffer needs 1 character

In any case can you please confirm what `Unicode.read_clipboard(&mut output).expect("Read text");` returns when you `empty` clipboard?

**Comment by jabbalaci** [comment]
Here is a sample program to reproduce this error:

```rust
use clipboard_win::formats::Unicode;
use clipboard_win::{Clipboard, Getter};

fn empty() {
    clipboard_win::raw::open().expect("open clipboard");
    clipboard_win::raw::empty().expect("empty clipboard");
}

fn get_text_windows() -> String {
    let _clip = Clipboard::new_attempts(10).expect("Open clipboard");
    let mut output = String::new();
    Unicode.read_clipboard(&mut output).expect("Read text");
    output
}

fn main() {
    empty();
    let text = get_text_windows();
    println!("text: {:?}", text);
}
```
`thread 'main' panicked at 'Read text: OS error 127'`, and the problematic line is `Unicode.read_clipboard(&mut output).expect("Read text");`

Thanks!
