### ISSUE TITLE
Unresolved Imports

### ISSUE THREAD

**Issue by Antonio-Bennett** [DoumanAsh/clipboard-win#25]
Hello sorry for my ignorance but I'm trying to build [win32yank](https://github.com/equalsraf/win32yank) and I keep getting unresolved import error as seen below. What is the possible reason?
![image](https://user-images.githubusercontent.com/31296212/210849612-ff93b24e-b587-4ced-921e-ba67163dda80.png) 
![image](https://user-images.githubusercontent.com/31296212/210849697-addf2692-64a5-4010-b3bb-47c917f8115e.png)

**Comment by DoumanAsh** [comment]
This is likely because you're not building for windows.
This repo is probably intended to be built targetting windows platform (as seen in name)
