### ISSUE TITLE
How do I clear the clipboard after I click the mouse to copy files

### ISSUE THREAD

**Issue by doraemonkeys** [DoumanAsh/clipboard-win#30]
The following code did not work:

```rust
 let _ = clipboard_win::empty();
```

```rust
let empty_data: &[&str] = &[];
let _ = formats::FileList.write_clipboard(empty_data);
```
version:
clipboard-win = "5.0"

**Comment by DoumanAsh** [comment]
@doraemonkeys `empty` should work, but you need to first create [Clipboard](https://docs.rs/clipboard-win/5.0.0/clipboard_win/struct.Clipboard.html) instance

Please do not ignore result of sys call, if you want to know why something doesn't work

**Comment by doraemonkeys** [comment]
I see. Thank you
