### ISSUE TITLE
Get clipboard data as HTML String?

### ISSUE THREAD

**Issue by DiscreteTom** [DoumanAsh/clipboard-win#31]
Thanks for this cool lib!

Any plan to add a feature to get clipboard data as HTML string? E.g. when code is copied from VSCode the highlight and background color info can be retrieved as HTML.

**Comment by DoumanAsh** [comment]
It should not be very difficult to implement even with limited reference documentation from MS: https://learn.microsoft.com/en-us/windows/win32/dataxchg/html-clipboard-format

But I never had need for something beyond text so I'm not sure when I plan to get around to do it.

**Comment by DoumanAsh** [comment]
I did quick prototype for HTML reading actually, turns out to be quite trivial
I'll maybe do it fully on this week I guess

**Comment by DoumanAsh** [comment]
@DiscreteTom You can give a go to my PR
I implemented both setting and getting HTML via `formats::Html` struct that implements necessary traits

**Comment by DiscreteTom** [comment]
I just need to get the HTML so I only tested the getter functionality and it works perfectly, thanks!

**Comment by DoumanAsh** [comment]
I finalized HTML format and released it as `5.2.0`
