### ISSUE TITLE
Upgrade to libc 0.2

### ISSUE THREAD

**Issue by frewsxcv** [DoumanAsh/clipboard-win#4]

**Comment by DoumanAsh** [comment]
Hm... well i don't mind, but with hard-coded dependency on libc everyone would need to make periodical pushes to bump versions.

And lol... i noticed that i don't need libc at all

**Comment by DoumanAsh** [comment]
Removed in https://github.com/DoumanAsh/clipboard-win/commit/730f239337c984173749c63fdc379ab2da8f8678
So there is no libc and no problem

**Comment by frewsxcv** [comment]
Thanks!
