### ISSUE TITLE
Corrupted clipboard copy & paste in servo. Due to long opened clipboard?

### ISSUE THREAD

**Issue by DoumanAsh** [DoumanAsh/clipboard-win#8]
Reference https://github.com/servo/servo/issues/16459

Observation:
- Opened clipboard prevents other applications from accessing it (e.g. Firefox) 
    - But powershell seems to be able to do it
- Performing Clipboard operation from another application breaks your opened Clipboard

Conclusion:
- WinAPI isn't suitable to keep Clipboard open for long. Clipboard should be opened only to perform operations. IT should be stated in documentation

**Comment by est31** [comment]
As a suggestion, maybe not expose the `Clipboard` type to users, so that they must use the provided functions? This will make the API safe.

**Comment by DoumanAsh** [comment]
No, I believe it should be up to user to decide for himself.
It is going to be stated in documentation though so that user would be aware of potential risk.
Still it is pretty useful if you want to batch few clipboard operations without re-opening clipboard each time.

**Comment by est31** [comment]
I see, seems reasonable.
