### ISSUE TITLE
Should get_string remove a trailing null character? 

### ISSUE THREAD

**Issue by longborough** [DoumanAsh/clipboard-win#9]
Hi. Many thanks for clipboard-win -- for me a really useful crate!

After copying to the Windows clipboard from a command-line window, the result includes a trailing null character ("\u{0}"). Would it be sensible for clipboard-win to remove this?

Here's my test program (mwe3):

```
extern crate clipboard_win;
use clipboard_win::Clipboard;

use std::str;

fn main() {
    let result = Clipboard::new().unwrap().get_string().unwrap();
    println!("{:?}", result);
}
```

After a "normal" copy (from `vscode` in this case, but `emacs` and `notepad++` behave in the same way) to the clipboard, everything seems fine:

```
D:\Development\Rust\mwe3>target\debug\mwe3.exe
"    let result = Clipboard::new().unwrap().get_string().unwrap();\n"
```

However, in a terminal window (cmd.exe), after taking these steps:

1. Right-click and select mark
1. Mark a line of text with the mouse pointer
1. Hit enter to copy

here's the result (marked and copied the word "Catastrophe":

```
D:\Development\Rust\mwe3>echo Catastrophe
Catastrophe

D:\Development\Rust\mwe3>target\debug\mwe3.exe
"Catastrophe\u{0}\n"
```

**Comment by DoumanAsh** [comment]
Hm... that's funny.
Actually `raw::get_string` removes last null char. See https://github.com/DoumanAsh/clipboard-win/blob/master/src/raw.rs#L224-L232

But then why you still get another null char?
My only guess is that it seems cmd appends extra null char?

**Comment by longborough** [comment]
Yes, that would appear to be the case. 

One possible solution (without detailing the dependencies, borrowing, or unwrapping that may be necessary) might be to use `.trim_matches(char::from(0))`.

That way, you could catch as many nulls as needed.

**Comment by DoumanAsh** [comment]
I'm going to consider it.
But youu should be aware that it is not really expected to have multiple 0 chars at the end of string.

**Comment by DoumanAsh** [comment]
Can you please check my new commit to fix it https://github.com/DoumanAsh/clipboard-win/commit/0096c9878b8aba640dad3fa5f63aa75dff0a1b95

If everything is ok I'll publish new version.

**Comment by longborough** [comment]
Thank you very much. That appears to work very nicely. I'm most grateful.

I agree, multiple 0 characters is a no-no. But as [Jon Postel](https://en.wikiquote.org/wiki/Jon_Postel) taught us, "...follow a general principle of robustness: be conservative in what you do, be liberal in what you accept from others"

**Comment by longborough** [comment]
I'll close this, to save you the trouble. I hope that's OK.

**Comment by DoumanAsh** [comment]
That's good. I published new version `2.1.2` with this enhancement

**Comment by longborough** [comment]
Just to confirm: I am now running with 2.1.2 from crates.io, and everything is fine.

Thanks again.

**Comment by DoumanAsh** [comment]
Glad to hear that!

I did my best to make nice wrapper over windows's clipboard, but there might other problems.
`rust-clipboard` uses it this crate at full extent so feel free to rise issues directly here.
